In [1]:
import pandas as pd
data = pd.read_csv(r"mysmartprice.csv")
#used open source boston dataset

In [2]:
data
#printed data

,product name,processor price,camera specs rear,camera specs front,display size,ram of phone,storage,battery,android version,score by smartprice,first site,price in first site,second site,price in second site,Price of product(available)
0,Vivo V23 5G,MediaTek Dimensity 920 MT6877T Processor,64 + 8 + 2 MP Triple Rear Camera,50+8 MP Dual Front Camera,6.44 inches AMOLED Display,8 GB RAM,128 GB Storage,4200 mAh Battery,Android v12 OS,NaN,NaN,NaN,NaN,NaN,"29,990"
1,Vivo V23 Pro 5G,MediaTek Dimensity 1200 MT6893 Processor,108 + 8 + 2 MP Triple Rear Camera,50+8 MP Dual Front Camera,6.56 inches AMOLED Display,8 GB RAM,128 GB Storage,4300 mAh Battery,Android v12 OS,NaN,NaN,NaN,NaN,NaN,"38,990"
2,OnePlus Nord 2,MediaTek Dimensity 1200 MT6893 Processor,50 + 8 + 2 MP Triple Rear Camera,32 MP Front Camera,6.43 inches Fluid AMOLED Display,6 GB RAM,128 GB Storage,4500 mAh Battery,Android v11 OS,8.0,NaN,NaN,NaN,NaN,"27,999"
3,Xiaomi Redmi Note 11T 5G,MediaTek Dimensity 810 MT6833 Processor,50 + 8 MP Dual Rear Camera,16 MP Front Camera,6.6 inches IPS LCD Display,6 GB RAM,64 GB Storage,5000 mAh Battery,Android v11 OS,7.8,Amazon,"16,999",Flipkart,"18,885","16,999"
4,Xiaomi 11i HyperCharge,MediaTek Dimensity 920 MT6877T Processor,108 + 8 + 2 MP Triple Rear Camera,16 MP Front Camera,6.67 inches AMOLED Display,6 GB RAM,128 GB Storage,4500 mAh Battery,Android v11 OS,NaN,NaN,NaN,NaN,NaN,"26,999"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178,Realme 8 5G 64GB,MediaTek Dimensity 700 MT6833 Processor,48 + 2 + 2 MP Triple Rear Camera,16 MP Front Camera,6.5 inches IPS LCD Display,4 GB RAM,64 GB Storage,5000 mAh Battery,Android v11 OS,7.7,NaN,NaN,Flipkart,"15,499","15,499"
179,Xiaomi Mi 10T 8GB RAM,Qualcomm Snapdragon 865 Processor,64 + 13 + 5 MP Triple Rear Camera,20 MP Front Camera,6.67 inches IPS LCD Display,8 GB RAM,128 GB Storage,5000 mAh Battery,Android v10 (Q) OS,8.1,Amazon,"31,990",Flipkart,"29,999","29,999"
180,Huawei P40 Pro,HiSilicon Kirin 990 5G Processor,50 + 40 + 12 MP Triple Rear Camera,32 MP Front Camera,6.58 inches OLED Display,8 GB RAM,256 GB Storage,4200 mAh Battery,Android v10 (Q) OS,NaN,NaN,NaN,NaN,NaN,"68,990"
181,IQOO 7 256GB,Qualcomm Snapdragon 870 Processor,48 + 13 + 2 MP Triple Rear Camera,16 MP Front Camera,6.62 inches AMOLED Display,8 GB RAM,256 GB Storage,4400 mAh Battery,Android v11 OS,8.3,NaN,NaN,Amazon,"32,990","32,990"
182,Samsung Galaxy Fold 2,Qualcomm Snapdragon 865 Plus Processor,12 + 12 + 12 MP Triple Rear Camera,10+10 MP Dual Front Camera,7.6 inches Dynamic AMOLED Display,12 GB RAM,256 GB Storage,4500 mAh Battery,Android v10 (Q) OS,NaN,Flipkart,"1,49,999",Amazon,"1,23,290","1,23,290"

In [3]:
df = pd.DataFrame(data)
#assigned dataframes to variable df.

In [4]:
df.isnull()
#checked if any field in dataset is empty

,product name,processor price,camera specs rear,camera specs front,display size,ram of phone,storage,battery,android version,score by smartprice,first site,price in first site,second site,price in second site,Price of product(available)
0,False,False,False,False,False,False,False,False,False,True,True,True,True,True,False
1,False,False,False,False,False,False,False,False,False,True,True,True,True,True,False
2,False,False,False,False,False,False,False,False,False,False,True,True,True,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,True,True,True,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False
179,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
180,False,False,False,False,False,False,False,False,False,True,True,True,True,True,False
181,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False
182,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False

In [5]:
df.isnull().sum()

product name                    0
processor price                 0
camera specs rear               0
camera specs front              0
display size                    0
ram of phone                    0
storage                         0
battery                         0
android version                 0
score by smartprice            29
first site                     56
price in first site            56
second site                    92
price in second site           92
Price of product(available)     0
dtype: int64

In [6]:
df.describe()

       score by smartprice
count           154.000000
mean              7.973377
std               0.354069
min               7.000000
25%               7.800000
50%               8.000000
75%               8.200000
max               8.800000

In [7]:
df.shape
#dimensions of dataset.

(183, 15)

In [8]:
df.dtypes

product name                    object
processor price                 object
camera specs rear               object
camera specs front              object
display size                    object
ram of phone                    object
storage                         object
battery                         object
android version                 object
score by smartprice            float64
first site                      object
price in first site             object
second site                     object
price in second site            object
Price of product(available)     object
dtype: object

In [18]:
df["product name"]=df["product name"].astype("float")

ValueError: could not convert string to float: b'Vivo V23 5G'

In [16]:
df["android version"]=df["android version"].astype("|S")

In [17]:
df.dtypes

product name                      |S35
processor price                 object
camera specs rear               object
camera specs front              object
display size                    object
ram of phone                    object
storage                         object
battery                         object
android version                   |S18
score by smartprice            float64
first site                      object
price in first site             object
second site                     object
price in second site            object
Price of product(available)     object
dtype: object